// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { defineConfig } from 'prisma';

export default defineConfig({
  schema: {
    kind: 'single',
    filePath: './prisma/schema.prisma',
  },
  datasource: {
    url: process.env.DATABASE_URL,
  },
});
